 <?php

 $title = 'Projects';
 $this->headTitle($title);
 ?>
 <div class="page-header">
    <h1>
        <?= $this->escapeHtml($title); ?>
        <small><a href="<?= $this->url('home/default', array('controller'=>'product', 'action'=>'add'));?>">新增商品</a></small>
    </h1>
 </div>

<div class="col-xs-12">
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>商品名称</th>
                <th>商品类别</th>
                <th>说明</th>
                <th>图片</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
            <tr>
                <td><?= $this->escapeHtml($product->name);?></td>
                <td><?= $this->escapeHtml($project->category_id);?></td>
                <td><?= $this->escapeHtml($project->short_desc);?></td>
                <td></td>
                <td>
                    <a href="<?= $this->basePath('product/edit/id/' . $project->id);?>">Edit</a>
                    <a href="<?= $this->basePath('product/delete/id/' . $project->id);?>">Edit</a>
                 </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</div>
